# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField(blank=True)),
                ('horario_termino', models.TimeField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cantidad_personas', models.IntegerField(default=0, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_reserva', to='hcmfront.Empleado')),
                ('insumos', models.ManyToManyField(to='hcmfront.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField(default=0, null=True)),
                ('horario_desde', models.TimeField(blank=True)),
                ('horario_hasta', models.TimeField(blank=True)),
                ('insumos', models.ManyToManyField(to='hcmfront.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_solicitud', to='hcmfront.Empleado')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_solicitud', to='hcmfront.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sala',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_status', to='hcmfront.Status'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_reserva', to='hcmfront.Sala'),
        ),
    ]
