# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcmfront', '0002_auto_20180621_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='empleado',
        ),
    ]
